### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Poussinou** [JanmanX/EncryptTextApp#1]
Can you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release. You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).

That's pretty easy and very helpful for those of us who aren't using Google services.

**Comment by JanmanX** [comment]
I have marked the initial release.
I will look at the binaries sometime later (sorry, am busy at the moment)

**Comment by Poussinou** [comment]
No problem thanks 👍
