### ISSUE TITLE
F-Droid update

### ISSUE THREAD

**Issue by IzzySoft** [JanmanX/EncryptTextApp#10]
Unfortunately, F-Droid still only has v1.0 – which is most likely due to the fact that `versionCode` and `versionName` in your [`build.gradle`](https://github.com/JanmanX/EncryptTextApp/blob/1.2/app/build.gradle#L10) have never been updated and still say "1.0, 1" even at tag 1.2.

Could you please fix that at tag 1.2, so that gets built by F-Droid?

```gradle
        versionCode 3
        versionName "1.2"
```

would be fine there. Thanks!

**Comment by IzzySoft** [comment]
Any chance, @JanmanX?

**Comment by JanmanX** [comment]
Hi @IzzySoft,

Not used to use GitHub, so I did not see your request. I will get on it!
Thousands of apologies for the delay!

**Comment by IzzySoft** [comment]
Thanks @JanmanX – and no worries: better late than never :rofl:

**Comment by JanmanX** [comment]
Merged this in release 1.2.1
https://github.com/JanmanX/EncryptTextApp/releases/tag/1.2.1

Thanks again, @IzzySoft !
